"""Add security features and usage tracking

Revision ID: d2c7c8dd8243
Revises: 3042d6f8337d
Create Date: 2026-01-17 14:41:06.841879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c7c8dd8243'
down_revision = '3042d6f8337d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('api_key_created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('api_key_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('usage_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_quota', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_quota_reset', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('last_quota_reset')
        batch_op.drop_column('monthly_quota')
        batch_op.drop_column('usage_count')
        batch_op.drop_column('api_key_expires_at')
        batch_op.drop_column('api_key_created_at')
        batch_op.drop_column('last_activity')
        batch_op.drop_column('last_login')
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
